export const betaEmailAccess = [
  'will.upstr@gmail.com',
  'alan.jones.rios@gmail.com',
  'workermz@gmail.com',
  'workermzk@gmail.com',
  'comercial@alligaredigital.com.br',
  'alligare@gmail.com',
  'neri.couto@gmail.com',
  'gmgabrielmartins@hotmail.com',
  'wiltristao@gmail.com',
  'vagnerkellers@hotmail.com',
  'Ceo@marcosdaniels.com',
  'agathaatp@gmail.com',
  'vagnerkellers@hotmail.com',
  'arthur_parente@outlook.com',
  'joaovitorsouzaa78@gmail.com',
  'edinilsonslabey@gmail.com',
];
