/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/product": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          owner?: parameters["rowFilter.product.owner"];
          created_at?: parameters["rowFilter.product.created_at"];
          title?: parameters["rowFilter.product.title"];
          description?: parameters["rowFilter.product.description"];
          title_image?: parameters["rowFilter.product.title_image"];
          imagem?: parameters["rowFilter.product.imagem"];
          price?: parameters["rowFilter.product.price"];
          deliver?: parameters["rowFilter.product.deliver"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["product"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** product */
          product?: definitions["product"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          owner?: parameters["rowFilter.product.owner"];
          created_at?: parameters["rowFilter.product.created_at"];
          title?: parameters["rowFilter.product.title"];
          description?: parameters["rowFilter.product.description"];
          title_image?: parameters["rowFilter.product.title_image"];
          imagem?: parameters["rowFilter.product.imagem"];
          price?: parameters["rowFilter.product.price"];
          deliver?: parameters["rowFilter.product.deliver"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          owner?: parameters["rowFilter.product.owner"];
          created_at?: parameters["rowFilter.product.created_at"];
          title?: parameters["rowFilter.product.title"];
          description?: parameters["rowFilter.product.description"];
          title_image?: parameters["rowFilter.product.title_image"];
          imagem?: parameters["rowFilter.product.imagem"];
          price?: parameters["rowFilter.product.price"];
          deliver?: parameters["rowFilter.product.deliver"];
        };
        body: {
          /** product */
          product?: definitions["product"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profile": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          name?: parameters["rowFilter.profile.name"];
          plan?: parameters["rowFilter.profile.plan"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profile"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          name?: parameters["rowFilter.profile.name"];
          plan?: parameters["rowFilter.profile.plan"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profile.id"];
          created_at?: parameters["rowFilter.profile.created_at"];
          is_subscribed?: parameters["rowFilter.profile.is_subscribed"];
          interval?: parameters["rowFilter.profile.interval"];
          name?: parameters["rowFilter.profile.name"];
          plan?: parameters["rowFilter.profile.plan"];
        };
        body: {
          /** profile */
          profile?: definitions["profile"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  product: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    owner?: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    title?: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    title_image?: string;
    /** Format: text */
    imagem?: string;
    /**
     * Format: numeric
     * @default 0
     */
    price?: number;
    /** Format: text */
    deliver?: string;
  };
  profile: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: boolean
     * @default false
     */
    is_subscribed?: boolean;
    /** Format: text */
    interval?: string;
    /** Format: text */
    name?: string;
    /**
     * Format: text
     * @default free
     */
    plan: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description product */
  "body.product": definitions["product"];
  /** Format: bigint */
  "rowFilter.product.id": string;
  /** Format: uuid */
  "rowFilter.product.owner": string;
  /** Format: timestamp with time zone */
  "rowFilter.product.created_at": string;
  /** Format: text */
  "rowFilter.product.title": string;
  /** Format: text */
  "rowFilter.product.description": string;
  /** Format: text */
  "rowFilter.product.title_image": string;
  /** Format: text */
  "rowFilter.product.imagem": string;
  /** Format: numeric */
  "rowFilter.product.price": string;
  /** Format: text */
  "rowFilter.product.deliver": string;
  /** @description profile */
  "body.profile": definitions["profile"];
  /** Format: uuid */
  "rowFilter.profile.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.profile.created_at": string;
  /** Format: boolean */
  "rowFilter.profile.is_subscribed": string;
  /** Format: text */
  "rowFilter.profile.interval": string;
  /** Format: text */
  "rowFilter.profile.name": string;
  /** Format: text */
  "rowFilter.profile.plan": string;
}

export interface operations {}

export interface external {}
